"""Strip noise from HTML before passing it to an LLM.

Strategy: keep only the attributes that tell the LLM *what* a field is
(id, name, role, type, aria-*, value, placeholder). Strip everything
presentational (class, style, on*) and auto-generated (react-select-*,
css-*, radix-*). Remove empty leaf elements left behind by the cleaning.
"""
from __future__ import annotations

import re

from bs4 import BeautifulSoup, Comment

# Tags that add zero semantic value for field identification.
# Note: svg is handled separately in clean_html_for_llm to allow aria-label lifting.
_REMOVE_TAGS = frozenset({
    "script", "style", "noscript", "template",
    "link", "meta", "head", "img", "picture", "source",
})

# The ONLY attributes kept — everything else is dropped.
_KEEP_ATTRS = frozenset({
    "id", "name", "role", "type", "placeholder", "value",
    "for", "href", "action", "method",
    "aria-label", "aria-labelledby", "aria-placeholder",
    "aria-expanded", "aria-haspopup", "aria-controls",
    "aria-modal", "aria-checked", "aria-selected", "aria-required",
    "data-testid", "data-cy", "data-action",
    "checked", "selected", "multiple", "required", "readonly", "disabled",
    "title",
})

# IDs that are auto-generated by React, Radix, Emotion, etc. — useless for the LLM.
_AUTO_ID_RE = re.compile(
    r"^(react-select[-_]|radix-|css-\w|emotion-\w|sc-\w)", re.IGNORECASE
)

# Class tokens considered semantically meaningful — kept even without other info.
_SEMANTIC_CLASS_KEYWORDS = frozenset({
    "form-input", "combobox", "dropdown", "modal", "dialog",
    "autocomplete", "datepicker", "timepicker", "select", "input-wrapper",
    "search", "picker", "calendar",
})


def _keep_class_token(token: str) -> bool:
    t = token.lower()
    return any(kw in t for kw in _SEMANTIC_CLASS_KEYWORDS)


def clean_html_for_llm(html: str, preserve_svg_aria: bool = False) -> str:
    """Return a stripped version of *html* containing only what helps the LLM.

    When *preserve_svg_aria* is True, SVG elements that carry an aria-label are
    replaced with a <span aria-label="..."> before the SVG is removed. This
    preserves semantic labels (e.g. "Nº de plazas: 5") that would otherwise be lost.
    """
    if isinstance(html, bytes):
        html = html.decode("utf-8", errors="replace")

    soup = BeautifulSoup(html, "html.parser")

    # ── Pass 0: handle SVG elements ──────────────────────────────────────────
    # If preserve_svg_aria, lift aria-label to a <span> before removing the SVG.
    for svg in soup.find_all("svg"):
        label = svg.get("aria-label") if preserve_svg_aria else None
        if label:
            span = soup.new_tag("span", attrs={"aria-label": label})
            svg.replace_with(span)
        else:
            svg.decompose()

    # ── Pass 1: remove noise tags ────────────────────────────────────────────
    for tag in soup.find_all(_REMOVE_TAGS):
        tag.decompose()

    for node in soup.find_all(string=lambda t: isinstance(t, Comment)):
        node.extract()

    # ── Pass 2: remove invisible elements ────────────────────────────────────
    for tag in soup.find_all(True, attrs={"hidden": True}):
        tag.decompose()
    for tag in soup.find_all(True, style=True):
        if "display:none" in tag.get("style", "").replace(" ", "").lower():
            tag.decompose()

    # ── Pass 3: strip attributes aggressively ────────────────────────────────
    for tag in soup.find_all(True):
        new_attrs: dict = {}

        for attr, value in list(tag.attrs.items()):
            if attr not in _KEEP_ATTRS:
                continue

            # Strip auto-generated IDs (react-select-_r_4_-*, radix-*, css-*, …)
            if attr == "id":
                v = value if isinstance(value, str) else " ".join(value)
                if _AUTO_ID_RE.match(v):
                    continue

            new_attrs[attr] = value

        # Handle class separately: keep only semantically meaningful tokens.
        raw_class = tag.get("class")
        if raw_class:
            tokens = raw_class if isinstance(raw_class, list) else raw_class.split()
            kept = [t for t in tokens if _keep_class_token(t)]
            if kept:
                new_attrs["class"] = " ".join(kept)

        tag.attrs = new_attrs

    # ── Pass 4: remove elements empty after stripping ────────────────────────
    # Repeat until stable (nested empties resolved from innermost outward).
    changed = True
    while changed:
        changed = False
        for tag in soup.find_all(True):
            if tag.name in ("html", "head", "body", "form"):
                continue
            has_text = bool(tag.get_text(strip=True))
            has_attrs = bool(tag.attrs)
            has_children = bool(tag.find_all(True))
            if not has_text and not has_attrs and not has_children:
                tag.decompose()
                changed = True

    return str(soup)
