"""Add canonical market locations + provider_locations.location_id mapping.

`locations` is a catalog table (no tenant_id, no RLS): the canonical markets the
product compares (e.g. "alc-airport"). `provider_locations` keeps the provider's
own naming untouched (the scraper text) and gains a nullable FK to the canonical
market. Unmapped provider_locations (location_id IS NULL) are excluded from
market-filtered views. Mapping is a manual operator action. See
docs/DATA_MODEL.md §"Canonical market locations (catalog)".

This migration also seeds the only market in use today ("Alicante · Aeropuerto")
and maps the existing Alicante provider_locations to it.

Revision ID: p8q9r0s1t2u3
Revises: o7p8q9r0s1t2
"""
from alembic import op

revision = "p8q9r0s1t2u3"
down_revision = "o7p8q9r0s1t2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE locations (
            id          BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            code        TEXT        NOT NULL,
            name        TEXT        NOT NULL,
            created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT pk_locations PRIMARY KEY (id),
            CONSTRAINT uq_locations_code UNIQUE (code)
        )
    """)

    op.execute("""
        ALTER TABLE provider_locations
            ADD COLUMN location_id BIGINT NULL,
            ADD CONSTRAINT fk_provider_locations_location
                FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE SET NULL
    """)
    op.execute("""
        CREATE INDEX ix_provider_locations_location_id
            ON provider_locations (location_id)
    """)

    # Catalog table read at query time by the app role (inside tenant_context).
    op.execute("GRANT SELECT ON locations TO smart_rental_app")

    # Seed the single market in use today and map existing Alicante offices to it.
    op.execute("""
        INSERT INTO locations (code, name)
        VALUES ('alc-airport', 'Alicante · Aeropuerto')
    """)
    op.execute("""
        UPDATE provider_locations
        SET location_id = (SELECT id FROM locations WHERE code = 'alc-airport')
        WHERE location_name ILIKE '%alicante%'
    """)


def downgrade() -> None:
    op.execute("ALTER TABLE provider_locations DROP COLUMN IF EXISTS location_id")
    op.execute("DROP TABLE IF EXISTS locations CASCADE")
